hertz:
  address: ":8080"
  enable_pprof: true
  log_level: info
  log_file_name: "log/hertz.log"
  log_max_size: 10
  log_max_age: 3
  log_max_backups: 50
mysql:
  dsn: "meetplan:meetplan@tcp(127.0.0.1:3306)/meetplan?charset=utf8&parseTime=True&loc=Local"
redis:
  address: "127.0.0.1:6379"
  username: ""
  password: ""
  db: 0