version: '3.7'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./deploy/init/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=meetplan
      - MYSQL_USER=meetplan
      - MYSQL_PASSWORD=meetplan
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./deploy/init/redis/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    privileged: true
#  Etcd:
#    image: 'bitnami/etcd:latest'
#    environment:
#      - ALLOW_NONE_AUTHENTICATION=yes
#      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
#    ports:
#      - "2379:2379"
#      - "2380:2380"